name: schoolsto
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  font_awesome_flutter: ^10.5.0
  flutter_polyline_points: ^2.0.0
  get: ^4.6.6
  shared_preferences:
  connectivity_plus: ^4.0.2
  google_maps_flutter: ^2.5.0
  csc_picker: ^0.2.7
  ionicons: ^0.2.2
  flutter_switch: ^0.3.2
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.4
  cloud_firestore: ^5.4.4
  image_picker: ^1.0.4
  location:
  dio:

  http: ^1.1.0
  intl_phone_number_input:
  onesignal_flutter: ^5.2.6
  geolocator: ^13.0.1
  intl:
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0

  google_nav_bar: ^5.0.6
  firebase_core: ^3.6.0
  permission_handler: ^11.3.1
  url_launcher:
  path:
  path_provider:
  lite_rolling_switch:

  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: RedHatDisplay
      fonts:
        - asset: assets/fonts/RedHatDisplay-VariableFont_wght.ttf

    - family: RedHatMedium
      fonts:
        - asset: assets/fonts/RedHatDisplay-Medium.ttf

    - family: RedHatLight
      fonts:
        - asset: assets/fonts/RedHatDisplay-Light.ttf
